# install python environments
echo "安装python环境 ..."
$rospip install -r requirements.txt


echo ""
echo ""

echo "导出yolov8s onnx ..."
$rospy export-det.py \
--weights yolov8s.pt \
--iou-thres 0.65 \
--conf-thres 0.25 \
--topk 100 \
--opset 11 \
--sim \
--input-shape 1 3 640 640 \
--device cuda:0

echo ""
echo ""


echo "转为enginefile ..."
/usr/local/TensorRT/bin/trtexec   --onnx=yolov8s.onnx --saveEngine=yolov8s.engine --fp16
echo ""
echo ""